import Head from "next/head";
import axios from "axios";

import { GetServerSidePropsContext } from "next";
import build_client from "../../api/build-client";

export async function getServerSideProps(context: GetServerSidePropsContext) {
    console.log('Landing Page!')

    try {
      const { data } = await build_client(context).get("/api/users/currentuser");
      
      return { props: data };
    } catch (err) {

       if (axios.isAxiosError(err) && err.response) {
        console.log(err.response.data);
         return { props: err.response.data };
       }

       return { props: { error: "An unexpected error occurred" } };
    }
    
}

interface CurrentUser {
  id: string;
  email: string;
}

export default function LandingPage({ currentUser }: { currentUser: CurrentUser }) {  
  console.log(currentUser);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {currentUser ? <h1>Welcome {currentUser.email}</h1> : <h1>You are not signed in</h1>}
      </div>
      
    </>
  );
}
